### ISSUE TITLE
Frequency filtered output file

### ISSUE THREAD

**Issue by AdoNunes** [FCP-INDI/C-PAC#553] opened 2016-08-28 17:23 UTC
Hi,
I am using CPAC to get a 0.1-0.01 frequency filtered resting fmri in the individual space with the first four volumes removed, nuisance variables regressed out/subtracted, motion corrected and skull striped. 
Is there a way to check that all this processes have been done? The filtered output is: functional_freq_filtered/_scan_rest_1_rest/_bandpass_freqs_0.01.0.1/bandpassed_demeaned_filtered.nii.gz

However, it seems that the first four volumes are not removed, either in the filtered or the preprocessed functional. If I check the preprocessed with the name rest_calc_tshift_resample_volreg_calc_maths.nii.gz against the raw, clearly the first four volumes have not been removed. If this step has not been done, maybe the other haven't been done. When I compare the time series from the raw and the preprocessed there are small changes that might indicate either motion correction or the nuisance correction.

I will appreciate some light on this issues.

Thanks,
Adonay

**Comment by ccraddock** [comment] 2016-08-28 18:46
Hello Adonay,

If you want to verify that the data has been bandpassed, you can do a FFT
of the data, and it should be 0 outside of the band of interest. This can
be done either by loading the data into matlab or using the AFNI gui.

John will be in touch to help with the other problems you are seeing. He
will probably want to see your configuration file and your subject list to
help him diagnose the problem. How many data points do you have to begin
with? And how many are in your final data? You can determine this using
3dinfo.

-cc

**Comment by adonayn** [comment] 2016-08-28 23:04
Hello Craddock,

I did FFT on the time series and the activity seems to be contained in the 0.1-0.01 hz, however, I will confirm it tomorrow. 

I have a 180 data points both in the raw and filtered (I did not do scrubbing).

Thanks,
Adonay

**Comment by jpellman** [comment] 2016-08-29 14:32
Hi @adonayn ,

As Cameron stated, the first step in troubleshooting this would be to look at your subject list and pipeline configuration YAML.  Would you be willing to post those here on Github?  If you would prefer more privacy you can also send them to me directly at john.pellman@childmind.org.

**Comment by adonayn** [comment] 2016-08-29 15:20
Hi john,

Though here is fine, maybe other people face the same in the future.
I have attached the configuration file, the subject list file and the file
to load the subjects.

Thanks
Adonay

**Comment by jpellman** [comment] 2016-08-29 15:30
Hi @adonayn ,

I don't see the files in the Github interface, and I don't think that Github can accept attachments when they are sent via e-mail.  Would you be able to attach them again using the Github interface directly rather than e-mail?

Many thanks,
John

**Comment by adonayn** [comment] 2016-08-29 15:34
Sure, I had to compress them separately though. 

Thanks
Adonay

[pipeline_config_cpac_abide_to_FS.yml.zip](https://github.com/FCP-INDI/C-PAC/files/442732/pipeline_config_cpac_abide_to_FS.yml.zip)
[subjescts_list_mypre_NYU.yaml.zip](https://github.com/FCP-INDI/C-PAC/files/442733/subjescts_list_mypre_NYU.yaml.zip)
[CPAC_subject_list_prep_func.yml.zip](https://github.com/FCP-INDI/C-PAC/files/442734/CPAC_subject_list_prep_func.yml.zip)

**Comment by jpellman** [comment] 2016-08-29 20:35
Hi @adonayn ,

The issue is that your subject list has 'scan_parameters' defined for every subject.  When this field is defined in the subject list, C-PAC preferentially uses the values contained within it over any settings that you have input into the GUI.  

The 'scan_parameters' field is populated based on the contents of the scan parameters CSV ( _/Users/adonay/Desktop/data/ABIDE/scan_parameters_abide_NYU.csv_ in this case).  If you edit this CSV so that the value of startIdx is '5' and then regenerate the subject list and re-run the pipeline, the first four volumes should be removed in the output files.

Alternatively, you can omit the scan parameters CSV when you're generating a subject list, and then define the settings you wish to use completely within the GUI.

**Comment by adonayn** [comment] 2016-08-29 21:50
HI John,

Thanks for taking a look. 

Also, the filtered data that I get from /functional_freq_filtered/_scan_rest_1_rest/_bandpass_freqs_0.01.0.1/bandpassed_demeaned_filtered.nii.gz
Has gone through the same corrections as the preprocessed output, namely motion and nuisance correction and slice correction?
Thanks
Adonay

**Comment by jpellman** [comment] 2016-08-30 20:44
Hi @adonayn ,

Bandpass filtering occurs after nuisance regression in the pipeline (see [here](http://fcp-indi.github.io/docs/user/_images/processing_workflow.png) for a diagram detailing the order of execution), so the bandpassed output should have slice timing, motion and nuisance corrections applied.  The path to the bandpassed file should reflect this by having segmentation thresholds and the pipeline strategy as intermediate directories before you reach the NifTI.  For example, something like:

functional_freq_filtered/_scan_rest_1_rest/_scan_rest_1_rest/_csf_threshold_0.98/_gm_threshold_0.7/_wm_threshold_0.98/_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1/_bandpass_freqs_0.009.0.1/bandpassed_demeaned_filtered.nii.gz

If you are not seeing this directory structure then the nuisance correction is not being run.   Looking at your pipeline configuration YAML, this looks to be the case, since segmentation (necessary for white matter and CSF nuisance regression) is not enabled.  You'll want to enable that as well as anatomical preprocessing and anatomical registration to make sure that the bandpassed outputs have the corrections applied.

**Comment by anibalsolon** [comment] 2019-06-02 23:20
Thank you for the input on this matter @AdoNunes and @jpellman we will improve documentation to help users to identify the outputs within what has been executed.

I’m closing this issue because it has been inactive for some time now. Please, open a new issue if you face new problems or have questions.

**Closed by anibalsolon** 2019-06-02 23:20 UTC
Labels: 0 - Low Priority, docs, support
