### ISSUE TITLE
cpac_run.py shouldn't need wx

### ISSUE THREAD

**Issue by alexsavio** [FCP-INDI/C-PAC#441] opened 2015-02-05 21:25 UTC
AFAIK, C-PAC is a tool run exclusively through python and command line. The GUI is an extra feature to help building the configuration files.

Why do you make wxPython a hard dependency? If I wanted to run C-PAC in a cluster, I shouldn't need to install an unnecessary GUI library in it.

Maybe I'm wrong and you do need wx. Could you please clear this to me?

Thank you very much for the hard work!

**Comment by jpellman** [comment] 2015-02-05 22:35
Hi Alexandre,

C-PAC was designed to be easy to use for researchers who otherwise might not have extensive programming/technical experience.  Hence, the GUI is an integral part of the package, which is why wxPython is a hard dependency.  It is not intended to be used strictly via the command line, although it can be executed in this manner if desired.

Best,
John Pellman

**Comment by alexsavio** [comment] 2015-02-05 22:39
Thanks John. I've just removed 'GUI' from CPAC/__init__.py. It wouldn't be complicated to make this optional anyway.

Cheers,
Alex

**Comment by danlurie** [comment] 2015-02-05 23:26
Can we re-open this? When we transitioned to the GUI and began requiring WX, my understanding was that we would eventually re-enable the ability to run entirely from the command line, which is a *really* important feature for a lot of people (including me). 

Maybe @alexsavio can do a pull request for this modification and we can add this as an option in a future release (or at least document the workaround on the User Guide).

**Comment by alexsavio** [comment] 2015-02-06 09:36
Sorry, I closed this, but if you agree I can start doing it.

**Comment by jpellman** [comment] 2015-02-06 14:12
Hi Alex and Dan,

We're about to do a code freeze after the release of C-PAC 0.3.9, followed by an extensive and much-needed code re-factoring.  At this time, we would thus prefer not to make any major changes to the C-PAC codebase, although our developers can take into account the possibility of decoupling the GUI from the YAML-based modules during the re-factoring.  As Alex said, it shouldn't be too difficult once we've decided how to tackle re-factoring.

**Comment by sgiavasis** [comment] 2015-02-11 21:54
CPAC can still be run from only the command line. If anything, this may be more of a documentation issue regarding how the YAML files can be hand-edited appropriately with the advent of new options and encodings.

**Comment by alexsavio** [comment] 2015-02-11 21:55
Yes, of course. If you edit the code and remove the GUI submodule. :)

Alexandre Manhães Savio  
PhD, Medical Imaging, Machine Learning
Grupo de Inteligencia Computacional UPV/EHU
home | email: alexsavio@gmail.com

**Comment by sgiavasis** [comment] 2015-02-11 21:59
Yes - but beyond the unnecessary wx import invoked through init, the makeup of the system is still so that at the heart of it all, CPAC can be run with one function.

We're coming up with a way to bypass the GUI call if wx is not available, and this will be implemented in 0.3.9. Thanks for the report!

**Comment by alexsavio** [comment] 2015-02-11 22:02
Yes, I know. I used it some time ago before you had the GUI.

I pushed the Condor job submission code (I don’t know if still works, btw)

Thanks,

Alexandre Manhães Savio  
PhD, Medical Imaging, Machine Learning
Grupo de Inteligencia Computacional UPV/EHU
home | email: alexsavio@gmail.com

**Comment by dclark87** [comment] 2015-02-11 22:18
I made this fix in commit https://github.com/FCP-INDI/C-PAC/commit/9e27274a7c667adfc10346604bd2fedeafb5eb17. This will be in the 0.3.9 release

**Closed by dclark87** 2015-02-11 22:18 UTC
