### ISSUE TITLE
🐛 Filepaths for extracted timeseries are missing an underscore

### ISSUE THREAD

**Issue by gkiar** [FCP-INDI/C-PAC#1692] opened 2022-02-24 14:49 UTC
### Describe the bug

When doing timeseries extraction and connectome estimation, I get a filepath like the following:

`sub-A007_ses-BAS1_task-rest_acq-645_atlas-Yeo-17space-MNI152NLin6res-1x1x1_desc-Mean-1_timeseries.1D`

Note, that there should be an underscore between the atlas (`Yeo-17`) and `space`.

Tiny bug, but thought I'd mention it :)

### To reproduce

Do timeseries extraction/connectome estimation.

### Expected behavior

An extra `_` between BIDS-related k-v pairs.

### Acceptance criteria

^ The above

**Comment by shnizzedy** [comment] 2022-02-24 22:09
Duplicate of #1641

**Closed by shnizzedy** 2022-02-24 22:09 UTC
Labels: bug

**Comment by gkiar** [comment] 2022-02-25 14:14
Thanks :sweat_smile:
