### ISSUE TITLE
SLURM job array time limit

### ISSUE THREAD

**Issue by ntraut** [FCP-INDI/C-PAC#664] opened 2017-07-05 11:19 UTC
Hi,

When running CPAC on a SLURM cluster, it sends a job array with time limit equals to `8*len(sublist)` hours. It would be useful to be able to specify that time because some people are not allowed to submit jobs which take more than 24h. Another solution would be to set time limit always at 8h because the time limit is for each job and not for the whole job array.

Another feature that would be nice would be to reprint on the screen the output of the job submission to confirm to the user that the job was submitted.

**Comment by sgiavasis** [comment] 2017-07-10 19:17
Hi ntraut,

Thank you for the suggestion- we'll take this into consideration for an upcoming release.

**Comment by nx10** [comment] 2023-02-08 19:10
Duplicate of #657

**Closed by nx10** 2023-02-08 19:10 UTC
Labels: feature, SLURM
