### ISSUE TITLE
Include extract_parameters.py in C-PAC

### ISSUE THREAD

**Issue by DaveOC90** [FCP-INDI/C-PAC#416] opened 2014-12-11 17:19 UTC
Hi,

It would be cool if the extract_parameters.py file used to concatenate the motion and power parameters from a C-PAC output was run automatically within C-PAC, and output at the end of a run.

Dave

**Comment by shnizzedy** [comment] 2020-06-09 16:47
Duplicate of #316

**Closed by shnizzedy** 2020-06-09 16:47 UTC
Labels: improvement
