### ISSUE TITLE
Could not run node anat_skullstrip

### ISSUE THREAD

**Issue by dowd-a** [FCP-INDI/C-PAC#853] opened 2018-11-18 23:39 UTC
I've seen this error with two different data sets. For some reason the anat_skullstrip node is failing.

181118-23:18:32,58 nipype.workflow ERROR:
	 could not run node: resting_preproc_sub-00440_ses-1.anat_preproc_0.anat_skullstrip
181118-23:18:32,60 nipype.workflow INFO:
	 crashfile: /outputs/crash/crash-20181118-231229-dowda-anat_skullstrip-34b588d9-e714-4894-acc0-7d13b87a4a0c.pklz
181118-23:18:32,64 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/code/run.py", line 392, in <module>
    plugin='MultiProc', plugin_args=plugin_args)
  File "/code/CPAC/pipeline/cpac_runner.py", line 487, in run
    p_name, plugin, plugin_args)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 3769, in prep_workflow
    workflow.run(plugin=plugin, plugin_args=plugin_args)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by anibalsolon** [comment] 2018-11-19 00:03
Hi @dowd-a !

Could you please provide us with the crash file, so we can look further into your issue?
```
crash-20181118-231229-dowda-anat_skullstrip-34b588d9-e714-4894-acc0-7d13b87a4a0c.pklz
```

Thank you!

**Comment by dowd-a** [comment] 2018-11-19 00:58
Thanks for the quick response. I'm having a difficult time attaching the crash file because my computer doesn't recognize the file type. Is there a way you usually get around this?

**Comment by dowd-a** [comment] 2018-11-19 02:09
I shelled into the C-PAC singularity container (converted from docker) and used the nipypecli crash command. I got the following error.

Singularity c-pac-latest.simg:/corral-secure/utdmc/Dell-Medical-Imaging/skull_stripping_study/cpac-out> nipypecli crash crash/crash-20181118-231229-dowda-anat_skullstrip-34b588d9-e714-4894-acc0-7d13b87a4a0c.pklz 
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/nipypecli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/scripts/cli.py", line 94, in crash
    display_crash_file(crashfile, rerun, debug, dir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/scripts/crash_files.py", line 51, in display_crash_file
    crash_data = loadcrash(crashfile)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 632, in loadcrash
    return loadpkl(infile, versioning=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 683, in loadpkl
    raise e
traits.trait_errors.TraitError: The trait 'in_file' of a SkullStripInputSpec instance is an existing file name, but the path  '/scratch/working/resting_preproc_sub-00440_ses-1/anat_preproc_0/anat_reorient/sub-00440_T1w_resample.nii.gz' does not exist.



Do I need to have access to the scratch directory to read the crash file? And if so, what do I do if I am running C-PAC in a container?

**Comment by anibalsolon** [comment] 2018-11-19 02:46
Great point! During the unserialization (loading the crash file), some validations are made and, for this case, the file must exist.

When running C-PAC, you can bind `/scratch` in a host folder, such as a folder inside `/tmp` :

```
docker run ... -v /tmp/cpac_runs:/scratch ... childmind/c-pac
```

**Comment by dowd-a** [comment] 2018-11-19 02:56
Yes, so I did bind the /scratch folder to /tmp, but then how do I modify the file paths that the crash file is looking for?

**Comment by anibalsolon** [comment] 2018-11-19 03:01
You do not need to change the paths if you run the nipypecli command within docker (i.e. shelled), because it will be mapped to the correct paths.

**Comment by dowd-a** [comment] 2018-11-19 03:03
Oh, I see. I'll try that.

**Comment by dowd-a** [comment] 2018-11-19 03:12
Okay here is the crash file.


File: /outputs/crash/crash-20181118-232930-dowda-anat_skullstrip-953222d9-b3fd-4d1b-b56f-f3586f6921be.pklz
Node: resting_preproc_sub-0027229_ses-1.anat_preproc_0.anat_skullstrip
Working directory: /scratch/working/resting_preproc_sub-0027229_ses-1/anat_preproc_0/anat_skullstrip


Node inputs:

args = 
environ = {}
in_file = /scratch/working/resting_preproc_sub-0027229_ses-1/anat_preproc_0/anat_reorient/sub-0027229_ses-1_run-1_T1w_resample.nii.gz
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/afni/base.py", line 110, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 1033, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 970, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
3dSkullStrip -input /scratch/working/resting_preproc_sub-0027229_ses-1/anat_preproc_0/anat_skullstrip/sub-0027229_ses-1_run-1_T1w_resample.nii.gz  -prefix sub-0027229_ses-1_run-1_T1w_resample_skullstrip.nii.gz
Standard output:

Standard error:
3dSkullStrip: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
Return code: 127

**Comment by anibalsolon** [comment] 2018-11-19 03:29
Thank you for finding it! I am working in a fix now, tomorrow morning it will be available as a new beta docker image.

**Comment by dowd-a** [comment] 2018-11-19 03:45
Thanks!

**Comment by anibalsolon** [comment] 2018-11-19 15:43
Quick update: we are moving to the FCP-INDI organization, so you can get the most updated docker image from there: 'fcpindi/c-pac:latest'

**Comment by dowd-a** [comment] 2018-11-19 16:22
Okay I just pulled the new image and am running it now. I was using [this](https://fcp-indi.github.io/docs/user/running.html) documentation, which has not yet been updated to reflect the move to FCP-INDI.

**Comment by anibalsolon** [comment] 2018-11-19 17:06
Yes, maybe the problem is during the conversion. Could you please try to run this command to generate a new singularity image?

```
docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v `pwd`:/output \
    --privileged -t --rm \
    singularityware/docker2singularity \
    fcpindi/c-pac:latest
```

and then try to run 3dSkullStrip from inside the singularity container.
Thanks!

**Comment by dowd-a** [comment] 2018-11-19 17:31
Is there no way to do it using a singularity command? I don't have access to docker on the super computer I'm using. 

I used the following command to pull the docker image and convert it:
`singularity pull --name c-pac-latest.simg docker://fcpindi/c-pac:latest`

**Comment by anibalsolon** [comment] 2018-11-19 17:54
Okay, I will try to reproduce with your command!

**Comment by dowd-a** [comment] 2018-11-19 18:29
Okay, so the workflow executed cleanly using the image created by the docker command you provided. So it must be an issue with the way singularity converts the docker image.

**Comment by anibalsolon** [comment] 2018-11-19 18:44
Yes, it is!

I've noticed during the conversion using your command this warning:

```
Exploding layer: sha256:bb2adcde00f2c84769f805e38962571e8ae6ef084572696f5f3b0df81848378e.tar.gz
Exploding layer: sha256:593a8e57163171ebfab4c517789de3a964490db7d3a8eeaf314ee93497321510.tar.gz
WARNING: Warning handling tar header: Can't create 'usr/lib/x86_64-linux-gnu/libgsl.so.19'
Exploding layer: sha256:3c1f571858506cd763da178b1905aadf4c1a35d97ff10b64966debd1b5adb777.tar.gz
```

That is the missing lib. 

I am rebuilding the Singularity image from Singularity Hub with the latests fcpindi/c-pac image, so I will soon give you insntructions on how to use it, instead of getting from docker hub.

If you want to try, you can copy the generated image using my command to your cluster, so it might work.

**Comment by dowd-a** [comment] 2018-11-19 18:54
Yes, I copied the image generated with docker to the cluster, and it works. Let me know if you are able to get the singularity hub version working.

Thanks!

**Comment by dowd-a** [comment] 2018-11-19 21:34
It worked! Thanks!

**Comment by anibalsolon** [comment] 2018-11-19 21:44
Great! If you have some comments on the experience of running C-PAC on Singularity, let us know!

**Closed by anibalsolon** 2018-11-19 21:44 UTC
