### ISSUE TITLE
Online pipeline design GUI

### ISSUE THREAD

**Issue by alfarmer8** [FCP-INDI/C-PAC#1325] opened 2020-07-15 09:58 UTC
C-PAC online pipeline design GUI keeps freezing or will not download the pipeline once it's created. This seems to be a problem with the webpage and not my connection.

**Comment by SucyLi** [comment] 2020-07-15 16:00
Hi thanks for reaching out! I just tried the [GUI](https://fcp-indi.github.io/C-PAC_GUI/versions/latest/browser/#/) and it works well on my end. Remember to duplicate the pipeline template first and then edit your custom pipeline. Could you clean cache or change another browser and try again? Let us know if it still doesn't work. 

<img width="267" alt="Screenshot 2020-07-15 11 56 52" src="https://user-images.githubusercontent.com/34257357/87567731-a4c32a00-c692-11ea-8552-937181368d31.png">

**Comment by alfarmer8** [comment] 2020-07-15 20:07
Thank you Xinhui. Now it will let me create a new pipeline, but it won't allow me to download the config file. I hit the cloud icon and nothing happens. I was able to successfully do this a couple days ago, but I realized that I needed to make some major changes to my custom pipeline. After returning to the website (and now after cleaning the cache), it won't let me get the config file after creating it. I am using Mozilla Firefox as my web browser. Any help is much appreciated.

Thank you,
Anna
________________________________

**Comment by SucyLi** [comment] 2020-07-15 20:20
Hi Anna, have you tried to clean cache? I use Chrome and I can download the config file without issues. The GUI code hasn't been changed for a month so I think the GUI per se should work if it worked for you a few days ago.

**Comment by alfarmer8** [comment] 2020-07-15 21:48
Thank you, Xinhui. I was able to Chrome to generate a config file, but some of the terms were undefined (see attached). I am trying to create a pipeline to register resting state fMRI data to the MNI pediatric template (which I have downloaded). It's pediatric data so unfortunately I don't think I can use the default pipeline. Thank you again for any additional help you can provide.

Anna
________________________________

**Comment by SucyLi** [comment] 2020-07-15 23:43
Hi Anna, 

No problem! Actually you can open the downloaded pipeline config in a text editor and change the template paths as needed. It doesn't necessarily have to be generated by GUI. I'd like to check those undefined fields in your current config but can't see the attached file. Would you mind sending it again to my CMI email: xinhui.li@childmind.org? 

Thanks,
Xinhui

**Comment by alfarmer8** [comment] 2020-07-17 07:37
Hi Xinhui,

I tried to run the attached pipeline in C-PAC tonight just to try it out on one subject and got the following errors. Please help if you can. I am still having trouble with the online pipeline generator. It still often doesn't allow me to create the .yml file after I make changes (I have tried in Firefox, Chrome, and Chromium and have systematically cleared the cache, cookies, the entire history both in the browsers and on my computer) so part of the attached pipeline configuration file was edited in the text editor.

Thank you,
Anna

docker run -i --rm \
>         -v /home/anna/NDARBIDS/test2/sub-ASDNDARAK289LJ9:/bids_dataset \
>         -v /home/anna/cpac/output:/outputs \
>         -v /tmp:/tmp \
>         -v /home/anna/cpac/pipelines:/configs \
>         -v /home/anna/cpac/resources:/resources \
>         fcpindi/c-pac:latest /bids_dataset /outputs participant --pipeline_file /configs/NDARnoderivs.yml

Running BIDS validator

#### Running C-PAC
Number of participants to run in parallel: 1
Input directory: /bids_dataset
Output directory: /outputs/output
Working directory: /home/anna/cpac/working
Crash directory: /outputs/crash
Log directory: /outputs/log
Remove working directory: False
Available memory: 6.0 (GB)
Available threads: 1
Number of threads for ANTs: 1
Starting participant level processing
Run called with config file /outputs/cpac_pipeline_config_2020-07-17T07-05-16Z.yml
200717-07:05:18,425 nipype.workflow INFO:


    C-PAC version: 1.6.2.a

    Setting maximum number of cores per participant to 1
    Setting number of participants at once to 1
    Setting OMP_NUM_THREADS to 1
    Setting MKL_NUM_THREADS to 1
    Setting ANTS/ITK thread usage to 1
    Maximum potential number of cores that might be used during this run: 1


Traceback (most recent call last):
  File "/code/run.py", line 590, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 342, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 323, in run_workflow
    subject_id, sub_dict, c, p_name, num_ants_cores
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 2034, in build_workflow
    if 0 in c.runDespike:
TypeError: argument of type 'bool' is not iterable
________________________________

**Comment by SucyLi** [comment] 2020-07-17 14:59
Hi Anna,

Sorry about the confusion and thank you for helping us to identify a bug in GUI! It's probably that we changed the type of runDespike, from boolean to list, but forgot to update in GUI. For now, try to change the field to `runDespike : [1]` in your text editor, and we'll fix this bug in next release. 

Regarding the GUI config file issue, it might be there's a bug in a field but we're not sure which field blocks you from downloading yet. Could you do me a favor? Try to download a default config without any modifications, if it works, you could modify the fields that you need. I doubt that it'll prevent you from downloading starting from a specific field.

Xinhui

**Comment by alfarmer8** [comment] 2020-07-17 17:14
Hi Xinhui,

I downloaded the default pipeline and tried to modify it to include despiking, slice timing, to register the anatomical and functional files to my study template rather than the MNI standard, and to include no derivatives (see attached). There doesn't seem to be a crash log as it looks like it didn't get that far. Please help if you can.

Thank you,
Anna

docker run -i --rm \
>         -v /home/anna/NDARBIDS/test2/sub-ASDNDARAK289LJ9:/bids_dataset \
>         -v /home/anna/cpac/output:/outputs \
>         -v /tmp:/tmp \
>         -v /home/anna/cpac/pipelines:/configs \
>         -v /home/anna/cpac/resources:/resources \
>         fcpindi/c-pac:latest /bids_dataset /outputs participant \--pipeline_file /configs/Defaultmodified.yml

Running BIDS validator

#### Running C-PAC
Number of participants to run in parallel: 1
Input directory: /bids_dataset
Output directory: /outputs/output
Working directory: /home/anna/cpac/working
Crash directory: /outputs/crash
Log directory: /outputs/log
Remove working directory: False
Available memory: 6.0 (GB)
Available threads: 1
Number of threads for ANTs: 1
Starting participant level processing
Run called with config file /outputs/cpac_pipeline_config_2020-07-17T17-01-55Z.yml
Traceback (most recent call last):
  File "/code/CPAC/pipeline/cpac_runner.py", line 216, in run
    c = Configuration(yaml.safe_load(open(config_file, 'r')))
  File "/code/CPAC/utils/configuration.py", line 20, in __init__
    self.__update_attr()
  File "/code/CPAC/utils/configuration.py", line 89, in update_attr
    new_key = check_pattern(attr_value)
  File "/code/CPAC/utils/configuration.py", line 61, in check_pattern
    return check_pattern(Template(orig_key).substitute(pattern_map), tags=tags)
  File "/code/CPAC/utils/configuration.py", line 61, in check_pattern
    return check_pattern(Template(orig_key).substitute(pattern_map), tags=tags)
  File "/code/CPAC/utils/configuration.py", line 61, in check_pattern
    return check_pattern(Template(orig_key).substitute(pattern_map), tags=tags)
  [Previous line repeated 989 more times]
  File "/usr/local/miniconda/lib/python3.7/string.py", line 132, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/local/miniconda/lib/python3.7/string.py", line 123, in convert
    named = mo.group('named') or mo.group('braced')
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/run.py", line 590, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 236, in run
    "\n\n".format(config_file, e)
Exception: Error parsing config file: /outputs/cpac_pipeline_config_2020-07-17T17-01-55Z.yml

Error details:
    maximum recursion depth exceeded while calling a Python object

________________________________

**Comment by SucyLi** [comment] 2020-07-17 18:18
Hi Anna, could you send your pipeline config to xinhui.li@childmind.org again? I'd like to take a look and see what's wrong. Thanks.

**Comment by SucyLi** [comment] 2020-07-17 20:58
Hi Anna, 

I figured that the above error is caused by `FSLDIR: $FSLDIR`. Changing `FSLDIR: $FSLDIR` to `FSLDIR: FSLDIR` resolved this issue. Besides, I check your config carefully and have a few suggestions on following fields:

- template_based_segmentation. I saw you used [EPI_template] but EPI-based segmentation is usually used for rodent data so I'd suggest you change it to `template_based_segmentation: [None]`

- distortion_correction. This field should be a list instead of a string. It's another bug in GUI and we're fixing it now. Please change it to `distortion_correction :  ["PhaseDiff"]`

- runBBReg. If you want to register functional image to T1 first, turning on boundary-based registration will help to get a better result so I'd say `runBBReg :  [1]`

- template_brain_only_for_anat and template_skull_for_anat. Note that when you run docker, you need to map your local path to virtual path within docker, since you already specify `-v /home/anna/cpac/resources:/resources`, you should change paths as following: 
`template_brain_only_for_anat: /resources/NDAR_Full_192_template_brain.nii.gz`
`template_skull_for_anat: /resources/NDAR_Full_192_template.nii.gz`

Thank you for your patience. We really appreciate your feedback and will fix related issues.

Xinhui

**Comment by alfarmer8** [comment] 2020-07-18 17:28
Hi Xinhui,

Thank you for the advice. I made the changes you suggested except for the distortion correction, which I set to None since I don't have a field map to go with my scans and it looks like that is required based on the documentation. This time it looks like the program ran, but it still gave me a really scary looking warning (see below). See attached for the pipeline I used and logs. Thank you for your continued help.

Anna

    End of subject workflow resting_preproc_sub-ASDNDARAK289LJ9_ses-1

    CPAC run complete:

        Pipeline configuration: default
        Subject workflow: resting_preproc_sub-ASDNDARAK289LJ9_ses-1
        Elapsed run time (minutes): 36.93864996830622
        Timing information saved in /outputs/log/cpac_individual_timing_default.csv
        System time of start:      2020-07-18 16:38:20
        System time of completion: 2020-07-18 17:15:15


/code/CPAC/nuisance/bandpass.py:82: ComplexWarning: Casting complex values to real discards the imaginary part
  Y_bp[:, j] = ideal_bandpass(Yc[:, j], sample_period, bandpass_freqs)

________________________________

**Comment by SucyLi** [comment] 2020-07-20 16:58
Hi Anna, to be honest I am not sure why this warning happens and it may be related to your bandpass option in nuisance regressor settings. I wouldn't worry about it too much if the program keeps running.

**Comment by shnizzedy** [comment] 2020-07-21 19:21
The part of the code that's raising that warning is https://github.com/FCP-INDI/C-PAC/blob/ce26ba9a38cbd401cd405150eeed23b805007724/CPAC/nuisance/bandpass.py#L80-L82

Since [np.zeros_like](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html) is not given an optional `dtype`, `Y_bp` uses the dtype of the given array `Y` which is composed of real numbers. When [real_if_close](https://numpy.org/doc/stable/reference/generated/numpy.real_if_close.html) reassigns `Y_bp`, it won't recast that array from real to complex, so it gives you a warning that it's discarding the imaginary components of the complex array coming out of [ideal_bandpass](https://github.com/FCP-INDI/C-PAC/blob/ce26ba9a38cbd401cd405150eeed23b805007724/CPAC/nuisance/bandpass.py#L8-L44). That warning is nothing to be scared of, it's just for your information.

**Comment by alfarmer8** [comment] 2020-07-23 23:05
Thank you, Jon. I appreciate your response.

Anna
________________________________

**Closed** 2020-08-04 19:24 UTC
