### ISSUE TITLE
🐛 [User-reported Bug] Issue Using C-PAC+Docker

### ISSUE THREAD

**Issue by Evan1578** [FCP-INDI/C-PAC#1488] opened 2021-04-11 22:10 UTC
Hi all,

I am currently trying to try to run the default C-PAC pipeline through a Docker container using C-PAC Python package. However, after installing C-PAC and Docker, I am running into the error - "ModuleNotFoundError: No module named 'pwd' " with stack trace:

(venv) C:\Users\Evan\PycharmProjects\DataScienceProject\venv\TDAfMRI>cpac run --help
Traceback (most recent call last):
File "C:\Users\Evan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in run_module_as_main
return run_code(code, main_globals, None,
File "C:\Users\Evan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\Evan\PycharmProjects\DataScienceProject\venv\Scripts\cpac.exe_main.py", line 7, in
File "c:\users\evan\pycharmprojects\datascienceproject\venv\lib\site-packages\cpac_main.py", line 397, in run
main(parsed)
File "c:\users\evan\pycharmprojects\datascienceproject\venv\lib\site-packages\cpac_main.py", line 307, in main
Backends(**arg_vars).run(
File "c:\users\evan\pycharmprojects\datascienceproject\venv\lib\site-packages\cpac\backends_init_.py", line 20, in Backends
from .docker import Docker
File "c:\users\evan\pycharmprojects\datascienceproject\venv\lib\site-packages\cpac\backends\docker.py", line 6, in
from cpac.backends.platform import Backend, Platform_Meta
File "c:\users\evan\pycharmprojects\datascienceproject\venv\lib\site-packages\cpac\backends\platform.py", line 3, in
import pwd
ModuleNotFoundError: No module named 'pwd'

Does anyone understand this error and how it can be avoided? (I have not used CPAC or Docker before, so I apologize in advance if the cause of this issue is a silly mistake)

Version Details

Windows 10 x64 system
Python 3.8.8
Docker version 20.10.5, build 55c4c88

**Comment by shnizzedy** [comment] 2021-04-13 14:38
Duplicate of https://github.com/FCP-INDI/cpac/issues/15

**Closed by shnizzedy** 2021-04-13 14:38 UTC
Labels: Windows, feature, good first issue, improvement, support
